services:
  postgres:
    image: postgres:17
    container_name: retailhub-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: retailhub
      POSTGRES_USER: retailhub
      POSTGRES_PASSWORD: secret
    ports:
      - "5434:5432"
    volumes:
      - retailhub-data:/var/lib/postgresql/data

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: retailhub-zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    container_name: retailhub-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

volumes:
  retailhub-data:
