services:
  postgres:
    image: postgres:17
    container_name: retailhub-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: retailhub
      POSTGRES_USER: retailhub
      POSTGRES_PASSWORD: secret
    ports:
      - "5434:5432"
    volumes:
      - retailhub-data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.0
    container_name: retailhub-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms256m"
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    container_name: retailhub-kafka
    restart: unless-stopped
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_HEAP_OPTS=-Xmx200m -Xms200m
    depends_on:
      - zookeeper

  flyway:
    image: flyway/flyway:10.7.1-alpine
    container_name: retailhub-flyway
    command: -url=jdbc:postgresql://postgres:5432/retailhub -user=retailhub -password=secret -connectRetries=60 migrate
    volumes:
      - ./app/src/main/resources/db/migration:/flyway/sql
    depends_on:
      postgres:
        condition: service_started

  app:
    build: .
    container_name: retailhub-app
    restart: unless-stopped
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/retailhub
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_FLYWAY_ENABLED=false
      - APP_QR_SCAN_BASE_URL=http://185.221.199.141
      - APP_JWT_SECRET=beAxeaveJiJRK6CIwR_bp-DxQAH9BBRWkv5HfhZOVHVU4JWGA6MFSndFPFd_lE7keRxVpNcuKfopDNeBMfJRBQ
    depends_on:
      postgres:
        condition: service_started
      kafka:
        condition: service_started
      flyway:
        condition: service_completed_successfully

  nginx:
    image: nginx:alpine
    container_name: retailhub-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  retailhub-data:
